#!/bin/bash

# Install poetry via pip
pip install poetry

# Install dependencies
poetry install

# Install playwright and its dependencies
poetry run playwright install
poetry run playwright install-deps

export AIRFLOW_HOME=$(pwd)