S3_BUCKET = "housepriceetl"
RAW_DIR = "data/raw"
STAGING_DIR = "data/staging"
ZOOPLA_BASE_URL = "https://www.zoopla.co.uk/for-sale/property"
STAGING_TABLE = "dev.public.staging_table"
PROD_TABLE = "dev.public.prod_table"
