S3_BUCKET = "housepriceetl"
RAW_DIR = "data/raw"
STAGING_DIR = "data/staging"
ZOOPLA_DOMAIN = "https://www.zoopla.co.uk"
ZOOPLA_SEARCH_URL = ZOOPLA_DOMAIN + "/for-sale/property"
STAGING_TABLE = "dev.public.staging_table"
PROD_TABLE = "dev.public.prod_table"
